WizardOfWor (#79)
* added sprites and background/wall rendering

* added correct wall rendering

* added player and enemy rendering

* added annotations

* added teleporter, lives, enemy_bullet, player movement, radar

* added score and shooting

* added collision behavior, death & spawning

* added sprites and generic player movement

* game is fully playable?

* added scope notice

* added scope notice

* added some comments

* tidy up

* reduced step size back to 1

* updated observation_space.
The test still fail because of:
jax.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on traced array with shape int32[]

* fixed issues caused by faulty annotations and observation spaces